; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; build_flags = 
	; -DDEBUG_MODE_PRINT_SERIAL=1
	; -DCORE_DEBUG_LEVEL=5
    ; -DCONFIG_USB_HOST_ENABLED=1
	; -DESP_IDF_USB_ENABLED=1
	; -DCFG_TUSB_MCU=OPT_MCU_ESP32S3
	; -DCFG_TUH_ENABLED=1
	; -DCFG_TUH_RHPORT=0
	; -DCFG_TUH_HID=1
	; -DCONFIG_TINYUSB_HOST_ENABLED=1
; lib_deps = 
	; bblanchon/ArduinoJson@^7.4.2
	; adafruit/Adafruit TinyUSB Library@^3.7.2